// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PocBooking.BookingSimulator.Data;

#nullable disable

namespace PocBooking.BookingSimulator.Migrations
{
    [DbContext(typeof(SimulatorDbContext))]
    [Migration("20260325120000_AddTags")]
    partial class AddTags
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("PocBooking.BookingSimulator.Data.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConversationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversationReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConversationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("GuestParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NoReplyNeeded")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId")
                        .IsUnique();

                    b.HasIndex("GuestParticipantId");

                    b.HasIndex("PropertyId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("PocBooking.BookingSimulator.Data.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConversationId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SenderParticipantId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("SenderParticipantId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("PocBooking.BookingSimulator.Data.MessageSearchJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AfterUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BeforeUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("JobId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.ToTable("MessageSearchJobs");
                });

            modelBuilder.Entity("PocBooking.BookingSimulator.Data.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParticipantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParticipantType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId")
                        .IsUnique();

                    b.HasIndex("PropertyId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("PocBooking.BookingSimulator.Data.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId")
                        .IsUnique();

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("PocBooking.BookingSimulator.Data.Conversation", b =>
                {
                    b.HasOne("PocBooking.BookingSimulator.Data.Participant", "GuestParticipant")
                        .WithMany()
                        .HasForeignKey("GuestParticipantId");

                    b.HasOne("PocBooking.BookingSimulator.Data.Property", "Property")
                        .WithMany("Conversations")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuestParticipant");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PocBooking.BookingSimulator.Data.Message", b =>
                {
                    b.HasOne("PocBooking.BookingSimulator.Data.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PocBooking.BookingSimulator.Data.Participant", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("PocBooking.BookingSimulator.Data.Participant", b =>
                {
                    b.HasOne("PocBooking.BookingSimulator.Data.Property", "Property")
                        .WithMany("Participants")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PocBooking.BookingSimulator.Data.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("PocBooking.BookingSimulator.Data.Participant", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("PocBooking.BookingSimulator.Data.Property", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}

