// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PocBooking.Api.Data;

#nullable disable

namespace PocBooking.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260317153617_AddGuestNameAndConfirmationNumber")]
    partial class AddGuestNameAndConfirmationNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("PocBooking.Api.Data.GuestMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookingGuestId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InternalGuestId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookingGuestId")
                        .IsUnique();

                    b.ToTable("GuestMappings");
                });

            modelBuilder.Entity("PocBooking.Api.Data.NotificationInbox", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NotificationUuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.HasIndex("NotificationUuid")
                        .IsUnique();

                    b.ToTable("NotificationInbox");
                });

            modelBuilder.Entity("PocBooking.Api.Data.ProcessedMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("InternalGuestId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InternalReservationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("NotificationInboxId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ProcessedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NotificationInboxId")
                        .IsUnique();

                    b.ToTable("ProcessedMessages");
                });

            modelBuilder.Entity("PocBooking.Api.Data.ReservationMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BookingReservationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfirmationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InternalReservationId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookingReservationId")
                        .IsUnique();

                    b.ToTable("ReservationMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
